# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-27 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimproductimageassociation',
            name='dim_product',
        ),
        migrations.RemoveField(
            model_name='dimproduct',
            name='dim_product_keywords',
        ),
        migrations.RemoveField(
            model_name='dimproduct',
            name='dim_product_sizes',
        ),
        migrations.DeleteModel(
            name='DimProductImageAssociation',
        ),
        migrations.DeleteModel(
            name='DimProductKeyword',
        ),
        migrations.DeleteModel(
            name='DimProductSizeRange',
        ),
    ]
