# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-27 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ess', '0002_auto_20180628_0748'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dimmaterial',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='dimmaterial',
            name='dim_product',
        ),
        migrations.DeleteModel(
            name='DimMaterial',
        ),
    ]
