# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 02:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_console.MasterTable')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User permission',
                'verbose_name_plural': 'User permissions',
            },
        ),
        migrations.AlterModelOptions(
            name='grouppermissions',
            options={'verbose_name': 'Group permission', 'verbose_name_plural': 'Group permissions'},
        ),
    ]
