# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_console', '0002_auto_20171214_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppermissions',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='grouppermissions',
            old_name='master_table_id',
            new_name='master_table',
        ),
        migrations.RenameField(
            model_name='userpermissions',
            old_name='master_table_id',
            new_name='master_table',
        ),
        migrations.RenameField(
            model_name='userpermissions',
            old_name='user_id',
            new_name='user',
        ),
    ]
