# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_console', '0003_auto_20171214_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertable',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
