# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_console', '0004_mastertable_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertable',
            name='permission_type',
            field=models.CharField(default='table', max_length=100),
            preserve_default=False,
        ),
    ]
