# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_console', '0005_mastertable_permission_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('table', 'Table'), ('procedure', 'Procedure')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='grouppermissions',
            name='master_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_console.Item'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='master_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_console.Item'),
        ),
        migrations.DeleteModel(
            name='MasterTable',
        ),
    ]
