# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_console', '0007_auto_20171217_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='duration',
            field=models.IntegerField(blank=True, default=60, help_text='in seconds', null=True),
        ),
    ]
