# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_console', '0008_auto_20171217_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='completion_percentage',
            field=models.IntegerField(blank=True, default=0, help_text='(for procedure only)', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='end_dt',
            field=models.DateTimeField(blank=True, help_text='(for procedure only)', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sequence',
            field=models.IntegerField(blank=True, help_text='(for procedure only)', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='start_dt',
            field=models.DateTimeField(blank=True, help_text='(for procedure only)', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='duration',
            field=models.IntegerField(blank=True, default=60, help_text='in seconds (for procedure only)', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
