# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_console', '0009_auto_20171217_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppermissions',
            old_name='master_table',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='userpermissions',
            old_name='master_table',
            new_name='item',
        ),
    ]
