# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 11:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('app_console', '0010_auto_20171217_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredProcedureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='grouppermissions',
            unique_together=set([('group', 'item')]),
        ),
        migrations.AlterUniqueTogether(
            name='userpermissions',
            unique_together=set([('user', 'item')]),
        ),
    ]
