# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_console', '0011_auto_20180111_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='allows_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='permission_type',
            field=models.CharField(choices=[('table', 'Table'), ('procedure', 'Procedure'), ('rpc', 'RPC')], max_length=100),
        ),
    ]
