# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_table', models.CharField(max_length=100)),
                ('last_load_dt', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=100, unique=True)),
                ('relative_path', models.CharField(max_length=500)),
                ('absolute_path', models.CharField(max_length=500)),
                ('extension', models.CharField(max_length=30)),
                ('size', models.IntegerField(default=0)),
                ('last_modified_dt', models.DateTimeField()),
                ('last_modified_by', models.CharField(blank=True, max_length=500, null=True)),
                ('creation_dt', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Metadata',
            },
        ),
    ]
