# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-30 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pipeline', '0002_auto_20180528_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='sheet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='database_table',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='filename',
            field=models.CharField(max_length=100),
        ),
    ]
