# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-12 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pipeline', '0004_metadatapk_metadatarule'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='has_rule',
            field=models.BooleanField(default=True),
        ),
    ]
