# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-12 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pipeline', '0005_metadata_has_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatarule',
            name='rule',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
