# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pipeline', '0006_metadatarule_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='last_load_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
