# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_sourcing', '0003_dimproduct_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
