# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-12 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sourcing', '0004_uploadfile_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimproduct',
            name='is_placeholder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dimproduct',
            name='is_test_sample',
            field=models.BooleanField(default=False),
        ),
    ]
