# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sourcing', '0005_auto_20180413_0740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factallocationadhoc',
            options={'verbose_name': 'Test Report'},
        ),
        migrations.RemoveField(
            model_name='dimproduct',
            name='is_placeholder',
        ),
        migrations.RemoveField(
            model_name='dimproduct',
            name='is_test_sample',
        ),
    ]
