# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sourcing', '0008_dimtest_facttestreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimsample',
            name='contract_weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dimsample',
            name='dye_print_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dimsample',
            name='fabric_finish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dimsample',
            name='garment_finish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dimsample',
            name='label_fiber_content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dimsample',
            name='mc_division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dimsample',
            name='mid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dimsample',
            name='recommended_care_instructions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dimsample',
            name='recommended_fiber_content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dimsample',
            name='sample_with_luxury_fiber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dimsample',
            name='submitted_care_instructions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dimsample',
            name='yarn_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dimsample',
            name='has_style',
            field=models.BooleanField(default=True, verbose_name='style defined'),
        ),
        migrations.AlterField(
            model_name='dimsample',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
