# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-15 13:08
from __future__ import unicode_literals

import core.mixins_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sourcing', '0009_auto_20180424_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiber_content', models.CharField(max_length=100, unique=True)),
                ('fiber_construction', models.CharField(blank=True, max_length=100, null=True)),
                ('yarn_size', models.CharField(blank=True, max_length=100, null=True)),
                ('dim_product', models.ManyToManyField(to='app_sourcing.DimProduct')),
            ],
            options={
                'verbose_name': 'Material',
            },
            bases=(models.Model, core.mixins_model.ModelFormFieldNames),
        ),
        migrations.CreateModel(
            name='HelperProductSubclassMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim_product_subclass', models.CharField(max_length=100, verbose_name='product subclass')),
                ('fabric_fiber_content', models.CharField(max_length=100)),
                ('uom', models.CharField(max_length=500)),
                ('quantity', models.FloatField()),
            ],
            options={
                'verbose_name': 'Subclass-Fabric',
            },
            bases=(models.Model, core.mixins_model.ModelFormFieldNames),
        ),
        migrations.AlterUniqueTogether(
            name='helperproductsubclassmaterial',
            unique_together=set([('dim_product_subclass', 'fabric_fiber_content')]),
        ),
    ]
