# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-15 13:16
from __future__ import unicode_literals

import core.mixins_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sourcing', '0011_auto_20180515_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactMaterialConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity_xts', models.IntegerField(default=0)),
                ('material_volume_per_unit', models.IntegerField(default=0)),
                ('material_volume_total', models.FloatField(default=0)),
                ('dim_material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_sourcing.DimMaterial')),
                ('dim_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_sourcing.DimProduct')),
            ],
            options={
                'verbose_name': 'Material Consumption',
            },
            bases=(models.Model, core.mixins_model.ModelFormFieldNames),
        ),
        migrations.RenameField(
            model_name='helperproductsubclassmaterial',
            old_name='quantity',
            new_name='volume',
        ),
    ]
